language: cpp
compiler: clang
sudo: required
dist: trusty

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files

script:
  - qmake # -config release
  - make
